@host = https://localhost:7098

### Create Todo List item
POST {{host}}/api/todo-lists
Content-Type: application/json

{
  "title": "List 1"
}

### Create Todo List item, validate that it handles empty title
POST {{host}}/api/todo-lists
Content-Type: application/json

{
  "title": ""
}

### Create Todo List item, validate that it duplicate title
POST {{host}}/api/todo-lists
Content-Type: application/json

{
  "title": "List 1"
}